### ISSUE TITLE
Diagram does sometimes not show

### ISSUE THREAD

**Issue by soerendomroes** [kieler/klighd-vscode#78] opened 2022-05-13 08:01 UTC
Seen in klighd-vscode 0.2.1 in lingua franca extension.

**Comment by NiklasRentzCAU** [comment] 2022-05-16 17:14
I cannot reproduce this issue when using the current lf extension and this released 0.2.1 extension. Do we have any further information on which systems this occured?

Works for me on Ubuntu 20.04.4 with openjdk 17.0.3

**Comment by soerendomroes** [comment] 2022-05-17 07:01
Have you tried to open the diagram immediately after starting the server? What about after a "reload window"?

It may be a mac problem as detailed in this [this](https://github.com/lf-lang/vscode-lingua-franca/issues/27) issue. Maybe they call swt while not on the main thread?

What about spaces in file paths?

**Comment by NiklasRentzCAU** [comment] 2022-05-30 13:44
Will be fixed with kieler/KLighD#117

**Closed** 2022-05-31 11:03 UTC
Labels: bug, requires server change
