### ISSUE TITLE
Show details does not seem to persist the expanded status

### ISSUE THREAD

**Issue by soerendomroes** [kieler/klighd-vscode#135] opened 2023-03-31 07:24 UTC
If one exand everything using the "Show All Details" action, everything is expanded:
![Chrono](https://user-images.githubusercontent.com/6419799/229051312-52e5ee2a-0a43-4631-bb1c-e3a2e385acdc.svg)

If I now change something in a component that was expanded by this action, everything is collapsed again.

![Chrono2](https://user-images.githubusercontent.com/6419799/229051309-443615b1-420f-4d95-b350-1ab1d092b7a5.svg)
If I change something in a component that I manually opened, I can edit in it all I want.

This does work correctly in Eclipse but not in VS Code.

**Comment by lhstrh** [comment] 2023-05-06 05:50
Is there any progress on this front, @NiklasRentzCAU? Can we help?

**Comment by NiklasRentzCAU** [comment] 2023-05-08 07:23
@lhstrh I did not put any priority into this issue yet and only have a vague idea what could be the cause. If this is a pressing issue for you I will have a look into it, maybe next week.

**Comment by NiklasRentzCAU** [comment] 2023-07-11 10:38
Waiting for response in lf-lang/vscode-lingua-franca#103

**Comment by lhstrh** [comment] 2023-09-21 07:12
Looks like https://github.com/lf-lang/vscode-lingua-franca/issues/103 is waiting for this issue? Do we have a deadlock here? :laughing:

**Comment by NiklasRentzCAU** [comment] 2023-09-22 08:29
This issue was caused by a missing dependency of the LF extension and is not an issue of KLighD/KLighDJS. Closing.

**Closed by NiklasRentzCAU** 2023-09-22 08:29 UTC
Labels: invalid
