### ISSUE TITLE
Error in Diagram Synthesis

### ISSUE THREAD

**Issue by jjrev** [kieler/klighd-vscode#166] opened 2024-01-24 16:01 UTC
On a Windows 11 system with JDK 17 installed, I see the following error in VSCode when trying to display the diagram for *.lf source files:

```
An exception occurred during diagram synthesis\
java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: \\\c:\Users\xxxxxxxx\Development\lingua-franca\test\C\src\Deadline.lf
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.nio.file.Path.of(Path.java:147)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.CodeMap$Correspondence.tag(CodeMap.java:144)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.ASTUtils.toText(ASTUtils.java:693)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactionInstance.&lt;init&gt;(ReactionInstance.java:70)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.createReactionInstances(ReactorInstance.java:758)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.&lt;init&gt;(ReactorInstance.java:902)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.&lt;init&gt;(ReactorInstance.java:882)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.&lt;init&gt;(ReactorInstance.java:105)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:322)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:144)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.syntheses.AbstractDiagramSynthesis.transform(AbstractDiagramSynthesis.java:220)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.transform(ReinitializingDiagramSynthesisProxy.java:289)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:454)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:389)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:346)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater.lambda$6(KGraphDiagramUpdater.java:267)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.lambda$1(AbstractLanguageServer.java:117)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.configureAndRun(AbstractLanguageServer.java:96)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.lsp.LanguageDiagramServer.start(LanguageDiagramServer.java:111)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.lsp.LanguageDiagramServer.main(LanguageDiagramServer.java:107)
```

Google searches indicate there is something improper with how the Path is handled.  I suspect the triple backslash in the beginning of the Path is where things are going awry but not sure where that prefix is coming from.

**Comment by NiklasRentzCAU** [comment] 2024-01-24 16:19
As the relevant parts of the stack trace point to the LF Synthesis and some internal LF generator code I would like to ask @a-sr if he knows anything about this. In Windows 10 we never heard about such a problem, but I will try to reproduce this on a Windows 11 machine soon when I have access to one.
Does this happen for any model or just a specific one?

**Comment by jjrev** [comment] 2024-01-24 17:51
It happens for all the models I've tried (multiple *.lf files for C and Python languages).

**Comment by a-sr** [comment] 2024-01-25 11:25
It looks like a problem with the `ASTUtils`, which is used in both the code generation and the diagram synthesis. Yet, sometimes the methods are not written with both contexts in mind, causing errors in the diagram generation (e.g. https://github.com/lf-lang/lingua-franca/issues/1930).

@jjrev Could you please open an issue in the LF repo for this problem.

I will close this issue since it is not related to klighd-vscode.

**Closed by a-sr** 2024-01-25 11:25 UTC
