### ISSUE TITLE
Rendering can not be found (Smart Zoom)

### ISSUE THREAD

**Issue by fight4day** [kieler/klighd-vscode#91] opened 2022-06-01 15:11 UTC
When Smart Zoom is enabled, clicking on a (zoomed) label results in an error.

Steps to reproduce:
- main branch, latest commit
- with Smart Zoom enabled, zoom out until a label's size is increased
- click on that label
- error is logged on the console

![cannot-find-rendering](https://user-images.githubusercontent.com/61043946/171437954-7254aeec-0447-4f8a-9b79-61cb14a650ab.png)

**Comment by NiklasRentzCAU** [comment] 2022-06-02 06:46
Duplicate of #85

**Closed by NiklasRentzCAU** 2022-06-02 06:46 UTC
Labels: bug
